version: "3.9"

services:
  aboutme:
    container_name: aboutme
    image: aboutme
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      PORT: 3000

  front-nginx:
    container_name: aboutme-proxy
    image: nginx:stable-alpine3.17
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/next-server.conf:/etc/nginx/conf.d/next-server.conf
      - ./nginx/next-upstream.conf.template:/etc/nginx/templates/next-upstream.conf.template
      - ./nginx/mime.types:/etc/nginx/conf/mime.types
      - ./.logs:/etc/nginx/logs
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".template"
